### Creating a new datafrome with only pastdue data by removing 'Completed' & 'Current'
> Instead created several pastdue DFs and appended them together

In [17]:
loanDF3 = loanDF.copy()

In [48]:
# Create index of items to drop from dataframe
#  and LoanStatus == "Current"
completed = loanDF3.query('LoanStatus == "Completed"').index
current = loanDF3.query('LoanStatus == "Current"').index
#CompletedCurrent = completed + current --> I think this is adding each value together instead of merging the 2 datasets

In [23]:
# Drop/remove all loans that are designated 'current' or 'completed'
# The sample offers a rough review to check if intended rows were dropped/removed

loanDF3.drop(completed, inplace=True)
loanDF3.drop(current, inplace=True)
loanDF3.sample(15)

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
92767,AEF333908387099615547C3,146679,2007-06-04 13:58:35.370000000,D,36,Chargedoff,2008-02-13 00:00:00,0.2048,0.1975,0.1775,NaN,NaN,NaN,NaN,NaN,NaN,0,CA,Other,Full-time,62.0000,False,True,223133764057631067F3FD8,2007-05-22 18:21:37.710000000,600.0000,619.0000,1990-12-11 00:00:00,10.0000,10.0000,16.0000,8,346.0000,8.0000,16.0000,1.0000,1234.0000,3.0000,0.0000,0.0000,4320.0000,0.9600,112.0000,16.0000,0.8100,0.0000,0.1800,"$25,000-49,999",True,3466.6667,D51E339168560654449444B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2338,8.0000,81,16088,6500,2007-06-15 00:00:00,Q2 2007,274A338851160205149895D,240.7400,791.1800,405.4300,385.7500,-16.0400,-6.2500,6094.5700,6094.5700,0.0000,1.0000,0,0,0.0000,150
48976,B2693422324970359030485,341064,2008-05-29 10:15:09.413000000,D,36,Chargedoff,2010-06-11 00:00:00,0.3745,0.3500,0.3400,NaN,NaN,NaN,NaN,NaN,NaN,4,NH,Other,Retired,68.0000,False,False,NaN,2008-05-22 09:03:16.680000000,600.0000,619.0000,1994-10-17 00:00:00,4.0000,3.0000,17.0000,1,0.0000,2.0000,6.0000,3.0000,133.0000,8.0000,1.0000,0.0000,0.0000,0.0000,0.0000,13.0000,0.5600,1.0000,2.9900,"$1-24,999",True,166.6667,6739342255625095158E25B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489,25.0000,69,32579,3000,2008-06-10 00:00:00,Q2 2008,E8593416163780631CCC4B2,135.7100,2578.4900,1198.3500,1380.1400,-39.4300,0.0000,1801.6500,1801.6500,0.0000,1.0000,0,0,0.0000,12
21711,F88C34245065324751F377F,349788,2008-06-12 22:09:32.670000000,A,36,Chargedoff,2009-06-26 00:00:00,0.2350,0.2200,0.2100,NaN,NaN,NaN,NaN,NaN,NaN,3,NJ,Other,Self-employed,29.0000,True,False,NaN,2008-06-04 13:17:37.983000000,720.0000,739.0000,1992-09-01 00:00:00,19.0000,18.0000,42.0000,14,533.0000,1.0000,15.0000,0.0000,0.0000,0.0000,0.0000,0.0000,23965.0000,0.5500,18935.0000,40.0000,0.8000,0.0000,NaN,NaN,False,0.0000,59E93423508939202BD0243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1839,13.0000,69,33342,15000,2008-06-25 00:00:00,Q2 2008,FDD734230533485616268F3,572.8600,4010.0200,2193.9000,1816.1200,-82.5500,0.0000,12806.1000,12806.1000,0.0000,1.0000,1,1,100.0000,253
70181,C05333785627629792AC7C3,85698,2007-01-16 21:42:32.100000000,HR,36,Chargedoff,2009-05-31 00:00:00,0.2676,0.2600,0.2550,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,Other,Not available,NaN,False,True,NaN,2007-01-16 21:33:57.950000000,520.0000,539.0000,1966-04-02 00:00:00,NaN,NaN,21.0000,3,35.0000,3.0000,11.0000,1.0000,NaN,65.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0900,Not displayed,True,1500.0000,6F29337951988281778F668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1865,29.0000,86,6960,2550,2007-01-30 00:00:00,Q1 2007,9F1E3375068602058C0A46A,102.7400,2370.2800,1317.7900,1052.4900,-18.1400,-18.7000,1232.2200,1232.2100,0.0000,1.0000,0,0,0.0000,61
16810,D062353797980893825E06D,556079,2012-02-02 07:54:19.613000000,NaN,36,Chargedoff,2012-08-10 00:00:00,0.2425,0.2049,0.1949,0.1904,0.0890,0.1014,4.0000,C,6.0000,1,MN,Nurse's Aide,Employed,50.0000,False,False,NaN,2012-01-31 19:59:43,720.0000,739.0000,1995-10-01 00:00:00,1.0000,1.0000,18.0000,1,0.0000,2.0000,5.0000,0.0000,0.0000,19.0000,1.0000,0.0000,0.0000,0.0000,0.0000,15.0000,0.8600,0.0000,0.0500,"$25,000-49,999",True,3083.3333,846C3643403482824973B5C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,699,6.0000,25,60296,4000,2012-02-10 00:00:00,Q1 2012,2765353722312665993BDF3,149.6500,149.6500,84.5300,65.1200,-3.1800,0.0000,3915.4700,3915.4700,0.0000,1.0000,0,0,0.0000,80
47317,1BB1336520210369365BC0B,31433,2006-08-15 05:59:54.323000000,C,36,Defaulted,2007-02-19 00:00:00,0.2626,0.2550,0.2450,NaN,NaN,NaN,NaN,NaN,NaN,0,NH,Other,Not available,NaN,True,True,BAE93365625072437A1CBD9,2006-08-10 08:52:05.927000000,640.0000,659.0000,1990-03-01 00:00:00,NaN,NaN,45.0000,15,2550.0000,0.0000,3.0000,2.0000,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3600,Not displayed,True,9583.3333,AAFF33657980935795ACCE7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221,6.0000,91,2680,10001,2006-08-21 00:00:00,Q3 2006,9C283365443823643AB4917,400.2900,396.0400,183.6900,212.3500,-4.2500,0.0000,9817.3100,9817.3100,0.0000,1.0000,0,0,0.0000,3
62054,F77F35975066763569AE9E3,1102488,2013-12-22 07:30:16.510000000,NaN,36,Past Due (1-15 days),NaN,0.1319,0.1039,0.0939,0.0907,0.0299,0.0608,6.0000,A,8.0000,1,UT,NaN,Other,283.0000,True,False,NaN,2013-12-22 07:30:19,660.0000,679.0000,1991-07-23 00:00:00,7.0000,6.0000,31.0000,5,160.0000,1.0000,5.0000,0.0000,0.0000,0.0000,1.0000,0.0000,4030.0000,0.7500,1200.0000,23.0000,0.7500,0.0000,0.1400,"$50,000-74,999",True,5666.6667,15CA370092894014766F6CC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,NaN,3,122703,5054,2013-12-26 00:00:00,Q4 2013,7E0E3700834263016E35FCF,164.0100,162.5713,119.4100,43.1613,-4.2900,0.0000,0.0000,0.0000,0.0000,1.0000,0,0,0.0000,1
42022,F38D3384455877007106AEE,109738,2007-03-11 20:55:17.160000000,D,36,Chargedoff,2009-06-23 00:00:00,0.2978,0.2900,0.2800,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,Other,Full-time,19.0000,False,False,NaN,2007-03-08 11:43:40.380000000,600.0000,619.0000,1990-01-04 00:00:00,7.0000,7.0000,35.0000,5,91.0000,4.0000,18.0000,1.0000,494.0000,17.0000,1.0000,0.0000,1210.0000,0.5100,1061.0000,27.0000,0.4800,2.0000,0.1100,"$100,000+",True,11665.3333,04E5338374591801786FAF4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1842,28.0000,84,8855,10000,2007-03-22 00:00:00,Q1 2007,9E173383133070072C31FF3,419.0600,9219.3200,5048.3600,4170.9600,-143.8400,0.0000,4951.6100,4951.6400,0.0000,1.0000,0,0,0.0000,103
49240,1DA83553049390824445DB2,615478,2012-07-23 07:16:16.227000000,NaN,60,Defaulted,2013-06-29 00:00:00,0.3011,0.2747,0.2647,0.2581,0.1075,0.1506,3.0000,D,5.0000,2,GA,Other,Employed,106.0000,False,False,NaN,2012-07-23 07:16:14,620.0000,639.0000,2001-07-14 00:00:00,9.0000,7.0000,19.0000,6,377.0000,2.0000,4.0000,0.0000,0.0000,0.0000,0.0000,0.0000,13663.0000,0.8100,3037.0000,17.0000,1.0000,1.0000,0.3300,"$25,000-49,999",True,3250.0000,1F0B3656110725985B3C44F,1.0000,10.0000,10.0000,0.0000,0.0000,7000.0000,5578.3900,-92.0000,192,12.0000,20,71121,2500,2012-07-27 00:00:00,Q3 2012,779B3523866279179D62CD5,77.0400,462.2400,122.8900,339.3500,-12.3500,0.0000,2377.1100,2377.1100,0.0000,1.0000,0,0,0.0000,37
12344,A1953371043589123028C35,46934,2006-10-10 19:24:53.207000000,D,36,Chargedoff,2008-05-25 00:00:00,0.2074,0.2000,0.1950,NaN,NaN,NaN,NaN,NaN,NaN,0,IL,Retail Management,Not available,NaN,True,False,NaN,2006-10-10 19:16:53.477000000,620.0000,639.0000,2000-04-17 00:00:00,NaN,NaN,16.0000,7,274.0000,4.0000,20.0000,0.0000,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2300,Not displayed,True,5000.0000,AFAA33724711635244AB641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2236,19.0000,89,4183,8000,2006-10-25 00:00:00,Q4 2006,0C533370599687808A2C71C,297.3100,4137.3400,2350.2300,1787.1100,-32.7700,-84.2900,5649.7800,5649.7700,0.0000,1.0000,0,0,0.0000,65
90559,A9283546231152796BFCCB9,581453,2012-04-23 09:08:23.003000000,NaN,36,Chargedoff,2014-01-02 00:00:00,0.2526,0.2148,0.2048,0.2000,0.0890,0.1110,4.0000,C,7.0000,1,NJ,Professional,Employed,6.0000,False,False,NaN,2012-04-23 09:08:16,660.0000,679.0000,1999-10-18 00:00:00,8.0000,8.0000,52.0000,8,219.0000,0.0000,3.0000,0.0000,0.0000,4.0000,0.0000,0.0000,8591.0000,0.5800,5257.0000,28.0000,0.8500,2.0000,0.2400,"$50,000-74,999",True,5750.0000,E66A3650532147500AF2AB5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189,20.0000,22,64850,13000,2012-05-02 00:00:00,Q2 2012,BA3E35445068723517E5528,492.9900,7669.8500,4174.1900,3495.6600,-148.4100,-133.1100,8825.8100,8825.8100,0.0000,1.0000,0,0,0.0000,189
52966,FAED33944002432849B5670,161044,2007-06-30 15:39:48.043000000,C,36,Chargedoff,2010-01-07 00:00:00,0.2676,0.2600,0.2500,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,Sales - Commission,Self-employed,171.0000,True,True,BA20339049003131177064E,2007-06-21 19:37:37.020000000,640.0000,659.0000,1991-12-09 00:00:00,18.0000,15.0000,74.0000,10,1221.0000,7.0000,14.0000,0.0000,0.0000,0.0000,0.0000,0.0000,47268.0000,0.3100,25923.0000,60.0000,0.8500,1.0000,0.2100,"$100,000+",True,16813.5000,087C33933195767726A0409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1646,30.0000,80,16696,15000,2007-07-06 00:00:00,Q3 2007,2CA73392336313783385F14,604.3600,15109.0000,8954.7600,6154.2400,-225.1300,0.0000,6045.2400,6045.2400,0.0000,1.0000,0,0,0.0000,117
101294,43233373529753262BA1F72,63745,2006-11-19 05:27:37.540000000,HR,36,Chargedoff,2007-12-05 00:00:00,0.1781,0.1600,0.1450,NaN,NaN,NaN,NaN,NaN,NaN,0,NC,Nurse's Aide,Not available,NaN,False,True,FE113364863511529673D04,2006-11-19 04:42:10.970000000,480.0000,499.0000,2001-11-26 00:00:00,NaN,NaN,8.0000,0,0.0000,1.0000,7.0000,7.0000,NaN,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0200,Not displayed,True,1666.6667,215F3375235597507A894E4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2408,12.0000,87,5237,1000,2006-12-06 00:00:00,Q4 2006,74FF33694664879838AD8CB,35.1600,240.6700,158.9700,81.7000,-1.6300,-12.8100,861.7600,841.0300,0.0000,1.0000,0,0,0.0000,14
87212,EF9B3379628125338FC39AC,90014,2007-01-28 18:41:29.570000000,E,36,Chargedoff,2008-05-07 00:00:00,0.2962,0.2800,0.2450,NaN,NaN,NaN,NaN,NaN,NaN,0,TX,NaN,NaN,NaN,False,True,A48C336490143957101528C,2007-01-17 14:52:53.723000000,580.0000,599.0000,1996-09-28 00:00:00,NaN,NaN,42.0000,5,245.0000,4.0000,16.0000,10.0000,NaN,30.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4400,Not displayed,True,4916.6667,9C1B338066440767031716D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2041,15.0000,85,7202,1200,2007-02-07 00:00:00,Q1 2007,2A283365323926406216242,49.6400,472.7900,229.4100,243.3800,-3.6200,-61.4080,970.6000,857.9200,253.3100,1.0000,0,0,0.0000,16
82078,3E423559328380701AD265C,652167,2012-10-10 11:44:44.540000000,NaN,36,FinalPaymentInProgress,NaN,0.3580,0.3177,0.3077,0.2799,0.1625,0.1174,1.0000,HR,5.0000,1,CA,Administrative Assistant,Employed,95.0000,True,False,NaN,2012-10-10 11:44:42,680.0000,699.0000,1985-09-01 00:00:00,14.0000,14.0000,48.0000,15,302.0000,1.0000,10.0000,1.0000,588.0000,40.0000,0.0000,0.0000,3941.0000,0.4200,4499.0000,45.0000,0.7700,3.0000,0.1200,"$25,000-49,999",True,4000.0000,735E3664576446182F7266E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,17,76475,4000,2012-10-18 00:00:00,Q4 2012,75CD3558903209419945DEC,173.7100,2836.7200,1402.2700,1434.4500,-45.1500,0.0000,0.0000,0.0000,0.0000,1.0000,0,0,0.0000,60

In [ ]:
# Bin resizing, to transform the x-axis    
#bin_edges = np.arange(0, sqrt_trans(pokemon['weight'].max())+1, 1)

# Plot the scaled data
plt.hist(loanDF['ListingCategory (numeric)'], bins=20)

# Identify the tick-locations
tick_locs = np.arange(0, 21, 1)

# Apply x-ticks
plt.xticks(tick_locs, [str(x) for x in np.arange(0,21,1)]);

In [ ]:
# Show histogram of Loan Categories

g = sb.distplot(loanDF['ListingCategory (numeric)'])
g.set(xticks=np.arange(0,21,1));

#g.set_xticks([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
#g.set_xticklabels([str(x) for x in np.arange(0,21,1)]);

In [ ]:
# Create a new figure
fig2 = plt.figure()

# 1 row, 2 cols, subplot 1
#plt.subplot(1,2,1)

# The argument of add_axes represents the dimensions [left, bottom, width, height] of the new axes. 
# All quantities are in fractions of figure width and height.
ax5 = fig2.add_axes([0.125, 0.125, 0.775, 0.775], label='6th axes')

ax5.hist(data=loanDF, x='ListingCategory (numeric)');

ax5.set_xlabel('Listing Categories (numeric)')
ax5.set_ylabel('Count')
ax5.set(xticks=np.arange(0,21,1));

#ax5.set_xticks()